# Generated by Django 5.0.1 on 2024-01-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("releasedate", models.DateTimeField()),
                ("genre", models.CharField(max_length=32)),
                ("garde", models.DecimalField(decimal_places=1, max_digits=2)),
                ("runningtime", models.IntegerField(default=0)),
                ("content", models.TextField()),
                ("director", models.CharField(max_length=32)),
                ("actor", models.CharField(default="Unknown", max_length=32)),
            ],
        ),
    ]
