# Generated by Django 5.0.1 on 2024-01-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_rename_garde_review_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="releasedate",
            field=models.CharField(max_length=32),
        ),
    ]
