# Generated by Django 5.0.1 on 2024-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0003_alter_review_releasedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="grade",
            field=models.CharField(max_length=32),
        ),
    ]
