# Generated by Django 5.0.1 on 2024-01-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_alter_review_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="grade",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
