# Generated by Django 5.0.1 on 2024-01-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0005_alter_review_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="runningtimehour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="runningtimeminute",
            field=models.IntegerField(default=0),
        ),
    ]
