# Generated by Django 5.0.1 on 2024-01-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="has_liked",
            field=models.IntegerField(default=0),
        ),
    ]
