# Generated by Django 5.0.1 on 2024-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idea", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="select",
            field=models.BooleanField(default=False, verbose_name="찜하기"),
        ),
    ]
